import { prisma } from "./prisma";

async function main() {
  // Caribbean Stocks from Multiple Exchanges:
  // - ECSE (Eastern Caribbean Securities Exchange)
  // - JSE (Jamaica Stock Exchange)
  // - TTSE (Trinidad & Tobago Stock Exchange)
  // - BSE (Barbados Stock Exchange)
  const stocks = [
    // === ECSE (Eastern Caribbean Securities Exchange) ===
    {
      ticker: "BON",
      name: "The Bank of Nevis Ltd",
      sector: "BANKING",
      price: 3.00,
      change: 0.00,
      volume: 0,
      volatility: 0.06,
      description: "Serving the people of Nevis with pride.",
      isActive: true,
    },
    {
      ticker: "BOSV",
      name: "Bank of St. Vincent and the Grenadines",
      sector: "BANKING",
      price: 10.50,
      change: -0.90,
      volume: 0,
      volatility: 0.08,
      description: "Leading financial institution in St. Vincent and the Grenadines.",
      isActive: true,
    },
    {
      ticker: "CWKN",
      name: "Cable & Wireless St. Kitts & Nevis",
      sector: "TELECOM",
      price: 3.75,
      change: 0.00,
      volume: 0,
      volatility: 0.12,
      description: "Telecommunications provider serving St. Kitts and Nevis.",
      isActive: true,
    },
    {
      ticker: "DES",
      name: "Dominica Electricity Services",
      sector: "UTILITIES",
      price: 4.25,
      change: 0.00,
      volume: 0,
      volatility: 0.04,
      description: "Electricity services provider in Dominica.",
      isActive: true,
    },
    {
      ticker: "ECFH",
      name: "Eastern Caribbean Financial Holdings",
      sector: "BANKING",
      price: 12.50,
      change: 0.50,
      volume: 0,
      volatility: 0.07,
      description: "Regional financial services holding company.",
      isActive: true,
    },
    {
      ticker: "GCBL",
      name: "Grenada Co-operative Bank Ltd",
      sector: "BANKING",
      price: 9.25,
      change: -0.26,
      volume: 0,
      volatility: 0.06,
      description: "Cooperative banking services in Grenada.",
      isActive: true,
    },
    {
      ticker: "GESL",
      name: "Grenada Electricity Services",
      sector: "UTILITIES",
      price: 11.75,
      change: 0.05,
      volume: 0,
      volatility: 0.04,
      description: "Electricity generation and distribution in Grenada.",
      isActive: true,
    },
    {
      ticker: "GPCL",
      name: "Grace Kennedy (Caribbean) Ltd",
      sector: "CONGLOMERATE",
      price: 5.40,
      change: 0.00,
      volume: 0,
      volatility: 0.09,
      description: "Diversified Caribbean conglomerate.",
      isActive: true,
    },
    {
      ticker: "SKNB",
      name: "St. Kitts Nevis Anguilla National Bank",
      sector: "BANKING",
      price: 3.00,
      change: 0.00,
      volume: 0,
      volatility: 0.05,
      description: "The leading financial institution in the Federation.",
      isActive: true,
    },
    {
      ticker: "SLES",
      name: "St. Lucia Electricity Services",
      sector: "UTILITIES",
      price: 24.00,
      change: 0.00,
      volume: 0,
      volatility: 0.03,
      description: "Regional power company serving St. Lucia.",
      isActive: true,
    },
    {
      ticker: "SLH",
      name: "S.L. Horsford & Company Ltd.",
      sector: "RETAIL",
      price: 2.00,
      change: 0.00,
      volume: 0,
      volatility: 0.07,
      description: "Oldest trading company in St. Kitts, dealing in auto and building.",
      isActive: true,
    },
    {
      ticker: "TDC",
      name: "St. Kitts Nevis Anguilla Trading & Dev Co.",
      sector: "CONGLOMERATE",
      price: 1.30,
      change: 0.00,
      volume: 0,
      volatility: 0.08,
      description: "Diverse holdings in retail, insurance, and automotive.",
      isActive: true,
    },
    {
      ticker: "WIOC",
      name: "West Indies Oil Company",
      sector: "ENERGY",
      price: 56.00,
      change: 0.00,
      volume: 0,
      volatility: 0.15,
      description: "Regional petroleum products distributor.",
      isActive: true,
    },

    // === JSE (Jamaica Stock Exchange) ===
    {
      ticker: "NCB",
      name: "NCB Financial Group",
      sector: "BANKING",
      price: 142.50,
      change: 2.35,
      volume: 125000,
      volatility: 0.08,
      description: "Jamaica's largest financial services group offering banking, insurance, and wealth management.",
      isActive: true,
    },
    {
      ticker: "JMMBGL",
      name: "JMMB Group Limited",
      sector: "BANKING",
      price: 38.75,
      change: 0.85,
      volume: 89000,
      volatility: 0.10,
      description: "Regional financial services group with operations across the Caribbean.",
      isActive: true,
    },
    {
      ticker: "GK",
      name: "GraceKennedy Limited",
      sector: "CONGLOMERATE",
      price: 98.50,
      change: -1.20,
      volume: 67000,
      volatility: 0.07,
      description: "Leading Caribbean conglomerate in food, financial services, and hardware.",
      isActive: true,
    },
    {
      ticker: "WIG",
      name: "Wisynco Group Limited",
      sector: "CONSUMER",
      price: 18.25,
      change: 0.45,
      volume: 234000,
      volatility: 0.09,
      description: "Jamaica's largest beverage manufacturer and distributor.",
      isActive: true,
    },
    {
      ticker: "BPOW",
      name: "Barita Investments Limited",
      sector: "BANKING",
      price: 65.00,
      change: 1.50,
      volume: 45000,
      volatility: 0.12,
      description: "Full-service investment bank and securities dealer.",
      isActive: true,
    },
    {
      ticker: "SEP",
      name: "Seprod Limited",
      sector: "CONSUMER",
      price: 72.30,
      change: -0.80,
      volume: 31000,
      volatility: 0.08,
      description: "Major food manufacturer producing dairy, flour, and snack products.",
      isActive: true,
    },
    {
      ticker: "JSE",
      name: "Jamaica Stock Exchange",
      sector: "FINANCIAL",
      price: 25.50,
      change: 0.30,
      volume: 18000,
      volatility: 0.05,
      description: "The operator of Jamaica's securities exchange.",
      isActive: true,
    },
    {
      ticker: "JPAT",
      name: "Jamaica Producers Group",
      sector: "AGRICULTURE",
      price: 28.90,
      change: 0.65,
      volume: 22000,
      volatility: 0.11,
      description: "Agricultural company specializing in tropical fruits and snacks.",
      isActive: true,
    },

    // === TTSE (Trinidad & Tobago Stock Exchange) ===
    {
      ticker: "RFHL",
      name: "Republic Financial Holdings",
      sector: "BANKING",
      price: 155.00,
      change: 3.25,
      volume: 78000,
      volatility: 0.06,
      description: "Leading financial services group with operations across the Caribbean.",
      isActive: true,
    },
    {
      ticker: "FCI",
      name: "First Citizens Group",
      sector: "BANKING",
      price: 48.50,
      change: -0.45,
      volume: 56000,
      volatility: 0.07,
      description: "Trinidad's state-owned commercial bank offering comprehensive banking services.",
      isActive: true,
    },
    {
      ticker: "SBTT",
      name: "Scotiabank Trinidad & Tobago",
      sector: "BANKING",
      price: 72.00,
      change: 1.10,
      volume: 42000,
      volatility: 0.05,
      description: "Major commercial bank, subsidiary of Bank of Nova Scotia.",
      isActive: true,
    },
    {
      ticker: "ANSA",
      name: "ANSA McAL Limited",
      sector: "CONGLOMERATE",
      price: 68.25,
      change: 0.75,
      volume: 35000,
      volatility: 0.08,
      description: "Diversified conglomerate with automotive, manufacturing, and retail operations.",
      isActive: true,
    },
    {
      ticker: "GHL",
      name: "Guardian Holdings Limited",
      sector: "INSURANCE",
      price: 32.50,
      change: -0.25,
      volume: 28000,
      volatility: 0.09,
      description: "Regional insurance and financial services company.",
      isActive: true,
    },
    {
      ticker: "PLIPDECO",
      name: "Point Lisas Industrial Port",
      sector: "INDUSTRIAL",
      price: 5.80,
      change: 0.15,
      volume: 15000,
      volatility: 0.10,
      description: "Operator of Trinidad's major industrial estate and port facilities.",
      isActive: true,
    },
    {
      ticker: "NGL",
      name: "National Gas Company",
      sector: "ENERGY",
      price: 45.00,
      change: 2.50,
      volume: 52000,
      volatility: 0.14,
      description: "State-owned natural gas transmission and processing company.",
      isActive: true,
    },
    {
      ticker: "TTEL",
      name: "Trinidad & Tobago Electricity",
      sector: "UTILITIES",
      price: 28.75,
      change: 0.00,
      volume: 8000,
      volatility: 0.03,
      description: "National electricity generation and distribution company.",
      isActive: true,
    },

    // === BSE (Barbados Stock Exchange) ===
    {
      ticker: "BICO",
      name: "Barbados Ice Company",
      sector: "CONSUMER",
      price: 2.85,
      change: 0.10,
      volume: 12000,
      volatility: 0.06,
      description: "Manufacturer and distributor of ice cream and frozen products.",
      isActive: true,
    },
    {
      ticker: "BCB",
      name: "Barbados Commercial Bank",
      sector: "BANKING",
      price: 15.50,
      change: -0.30,
      volume: 9000,
      volatility: 0.07,
      description: "Commercial banking services in Barbados.",
      isActive: true,
    },
    {
      ticker: "FTC",
      name: "FirstCaribbean International Bank",
      sector: "BANKING",
      price: 3.25,
      change: 0.05,
      volume: 65000,
      volatility: 0.08,
      description: "Major regional bank serving the Caribbean with retail and corporate banking.",
      isActive: true,
    },
    {
      ticker: "CBL",
      name: "Cave Shepherd & Company",
      sector: "RETAIL",
      price: 4.10,
      change: 0.20,
      volume: 7500,
      volatility: 0.09,
      description: "Barbados' premier department store and retail group.",
      isActive: true,
    },
    {
      ticker: "WIB",
      name: "West India Biscuit Company",
      sector: "CONSUMER",
      price: 28.00,
      change: 0.50,
      volume: 4000,
      volatility: 0.05,
      description: "Manufacturer of biscuits and snack foods for the Caribbean market.",
      isActive: true,
    },
    {
      ticker: "BWIA",
      name: "Barbados Water Authority",
      sector: "UTILITIES",
      price: 6.75,
      change: 0.00,
      volume: 2500,
      volatility: 0.02,
      description: "Water supply and sewerage services in Barbados.",
      isActive: true,
    },
  ];

  for (const s of stocks) {
    const stock = await prisma.stock.upsert({
      where: { ticker: s.ticker },
      update: {
        price: s.price,
        change: s.change,
        name: s.name,
        sector: s.sector,
        volatility: s.volatility,
        description: s.description,
        isActive: s.isActive,
      },
      create: s,
    });

    // Create initial price history entry if it doesn't exist
    const existingHistory = await prisma.stockPrice.findFirst({
      where: { stockTicker: stock.ticker },
    });

    if (!existingHistory) {
      await prisma.stockPrice.create({
        data: {
          stockTicker: stock.ticker,
          price: stock.price,
          timestamp: new Date(),
        },
      });
    }
  }

  // Seed Educational News Events
  // prisma/seed.ts (Fixed Section)

  // Seed Educational News Events
  await prisma.newsEvent.createMany({
    data: [
      {
        headline: "Category 3 Hurricane Approaching",
        summary:
          "Severe weather expected to impact insurance and retail stocks across the region.",
        sector: "INSURANCE",
        magnitude: -0.15,
        duration: 120, // Example value
        sentiment: "POSITIVE", // Required field from Zod/Model
      },
      {
        headline: "Record Tourist Arrivals for Carnival",
        summary:
          "Increased spending projected to boost tourism and retail sector earnings.",
        sector: "TOURISM",
        magnitude: 0.1,
        duration: 90,
        sentiment: "POSITIVE",
      },
    ],
  });

  console.log(" Seeded Caricom Stocks & Events");
}

main()
  .catch((e) => console.error(e))
  .finally(async () => await prisma.$disconnect());
